export const FETCH_SEARCH_ITEMS = 'FETCH_SEARCH_ITEMS';
export const SUBMIT_ITEM = 'SUBMIT_ITEM';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const ADD_NEW_NOTIFICATION = 'ADD_NEW_NOTIFICATION';
