export const FETCH_SEARCH_ITEMS = 'FETCH_SEARCH_ITEMS';
export const SUBMIT_ITEM = 'SUBMIT_ITEM';
export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATION = 'RECIEVE_NEW_NOTIFICATION';
